version: "3.6"

x-app: &default-app
  restart: always
  environment:
    - "READIUM_DATABASE_HOST=${READIUM_DATABASE_HOST}"
    - "READIUM_DATABASE_PORT=${READIUM_DATABASE_PORT}"
    - "READIUM_DATABASE_USERNAME=${READIUM_DATABASE_USERNAME}"
    - "READIUM_DATABASE_PASSWORD=${READIUM_DATABASE_PASSWORD}"
    - "READIUM_LCPSERVER_HOST=https://${READIUM_LCPSERVER_HOST}"
    - "READIUM_LCPSERVER_PORT=${READIUM_LCPSERVER_PORT}"
    - "READIUM_LCPSERVER_DATABASE=${READIUM_LCPSERVER_DATABASE}"
    - "READIUM_LCPSERVER_USERNAME=${READIUM_LCPSERVER_USERNAME}"
    - "READIUM_LCPSERVER_PASSWORD=${READIUM_LCPSERVER_PASSWORD}"
    - "READIUM_LSDSERVER_HOST=https://${READIUM_LSDSERVER_HOST}"
    - "READIUM_LSDSERVER_PORT=${READIUM_LSDSERVER_PORT}"
    - "READIUM_LSDSERVER_DATABASE=${READIUM_LSDSERVER_DATABASE}"
    - "READIUM_FRONTEND_HOST=https://${READIUM_FRONTEND_HOST}"
    - "READIUM_FRONTEND_PORT=${READIUM_FRONTEND_PORT}"
    - "READIUM_FRONTEND_DATABASE=${READIUM_FRONTEND_DATABASE}"
    - "READIUM_ENC_CONTENT=/opt/readium/files/encrypted"
    - "READIUM_LCPSERVER_CONFIG=/etc/readium/config.yaml"
    - "READIUM_LSDSERVER_CONFIG=/etc/readium/config.yaml"
    - "READIUM_FRONTEND_CONFIG=/etc/readium/config.yaml"
    - "READIUM_CONTENT_S3_BUCKET=${READIUM_CONTENT_S3_BUCKET}"
    - "AWS_REGION=${AWS_REGION}"
    - "AWS_S3_USER=${AWS_S3_USER}"
    - "AWS_S3_KEY=${AWS_S3_KEY}"
    - "AWS_S3_SECRET=${AWS_S3_SECRET}"

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/root/.caddy
  database:
    image: postgres:12-alpine
    restart: always
    ports:
      - "${READIUM_DATABASE_EXTERNAL_PORT}:${READIUM_DATABASE_PORT}"
    environment:
      POSTGRES_PASSWORD: "${READIUM_DATABASE_PASSWORD}"
    volumes:
      - ./base-local/database/entrypoint:/docker-entrypoint-initdb.d/
      - "dbdata:/var/lib/postgresql/data"

  lcpserver:
    <<: *default-app
    image: "registry.gitlab.com/steppelink/r-and-d/readium/lcpserver:latest"
    ports:
      - "${READIUM_LCPSERVER_EXTERNAL_PORT}:${READIUM_LCPSERVER_PORT}"
    volumes:
      - "encfiles:/opt/readium/files/encrypted"
      - "./base-local/etc:/etc/readium"
    depends_on:
      - database

  lsdserver:
    <<: *default-app
    image: "registry.gitlab.com/steppelink/r-and-d/readium/lsdserver:latest"
    ports:
      - "${READIUM_LSDSERVER_EXTERNAL_PORT}:${READIUM_LSDSERVER_PORT}"
    volumes:
      - "./base-local/etc:/etc/readium"
    depends_on:
      - database

  testfrontend:
    <<: *default-app
    image: "registry.gitlab.com/steppelink/r-and-d/readium/testfrontend:latest"
    ports:
      - "${READIUM_FRONTEND_EXTERNAL_PORT}:${READIUM_FRONTEND_PORT}"
    volumes:
      - "encfiles:/opt/readium/files/encrypted"
      - "rawfiles:/opt/readium/files/raw"
      - "./base-local/etc:/etc/readium"
    depends_on:
      - database

volumes:
  encfiles:
  dbdata:
  rawfiles:
